### PR TITLE
fix the Enumset Parsing

### PR DESCRIPTION
**Pull request by Areontar**
should we also uptick the version number for this?

### CODE REVIEW

**Comment by jschloman** [comment]
Approve

**Comment by asummers** [comment]
Yes, uptick version for all changes. It gets too confusing otherwise with caches etc.

This should work, replacing whatever version you need to swap:

find `pwd` -name "pom.xml" |  xargs -n1 -I{} sh -c "sed -i '' 's/99.0.5/99.0.6/' {}"

**Comment by asummers** [comment]
Approve.

**Comment by louis89** [comment]
Approve

**Pull request merged**
